# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeb056fb211a1e96859efae9496f6e13087ae7ebe6977eff401eaaee45bb35cd54360d56e3f7fb6b7c9ff8a2ee2f648801165deb0472871288f3677a42237b82

test:
  secret_key_base: b174f5c9e8c20cd8276ac62bdf707de5831c69aed6945e6ad2c0c2094ac88952aab19f953830cbe6d55fdd3b46985fd4e016082aa27f54b0cc97221956b60e21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
